### PR TITLE
Add lazy collection support

### PR DESCRIPTION
**Pull request by Xint0-elab**
Hi Vitor,

First of all, thank you for creating this package. Please consider accepting this pull request to add support for LazyCollection and using a query cursor for generating CSV exports.

This also includes some minor changes:

- Set license to MIT in composer.json file.
- Remove composer.lock file and ignore it as recommended for library projects.
- Allow different versions of orchestra/testbench depending on laravel version support.

### CODE REVIEW

**Comment by Xint0-elab** [comment]
Hi @vitorccs can you take a look at this PR?

**Comment by vitorccs** [comment]
@Xint0-elab Thanks very much for contributing to the repository. 

I am a little busy in the next days, but I can review your PR by the end of March 27th.

I let you know as soon as I review it.

**Comment by Xint0-elab** [comment]
Hi @vitorccs, let me know if you have questions about this PR.

**Comment by vitorccs** [comment]
Hi @Xint0-elab I reviewed your code and asked for a couple of minor changes (e.g: use camelCase for variables). I am unable to help you since the commit came from your repository.

**Comment by Xint0-elab** [comment]
@vitorccs variables in camelCase is done. Do you have any other comments or suggestions?

**Pull request merged**
